baseURL = "https://www.felix-boerner.de"
languageCode = "en-US"
title = "Felix Börner"
copyright = "&copy; 2017 - 2024 Felix Börner"
theme = "hugo-split-theme"
enableRobotsTXT = true
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[params]
  author = "Felix Börner"
  description = "BizDevOps - Agility - Leadership"
  shareImage = "/images/portrait.jpg"
  twitterHandle = "felix_boerner"
  favicon = "favicon.ico"
  licensed = true

  [params.visual.image]
    enable = true
    file = "/images/portrait.jpg"

  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Facebook"
        url = "https://www.facebook.com/felix.boerner.de"

      [[params.links.list1.link]]
        text = "GitHub"
        url = "https://github.com/escalate"

      [[params.links.list1.link]]
        text = "X (Twitter)"
        url = "https://twitter.com/felix_boerner"

      [[params.links.list1.link]]
        text = "Xing"
        url = "https://www.xing.com/profile/Felix_Boerner2"

  [[params.links]]
    [params.links.list2]
      heading = "Legal"

      [[params.links.list2.link]]
        text = "Privacy Policy"
        url = "/privacy-policy"

      [[params.links.list2.link]]
        text = "Imprint"
        url = "/imprint"
